### ISSUE TITLE
Environment issue when using rbenv.

### ISSUE THREAD

**Issue by pelted** [Pallinder/rails-test-runner#3]
So the workaround I've found when having multiple ruby versions installed (OS X) with rbenv is to set the runner command like this:
```json
{
    "railsTestRunner.rspecCommand": " /Users/me/.rbenv/shims/ruby bin/rails test"
}
```

Any other way to get VS Code to use the correct shell environment when running this or other Tasks?

**Comment by Pallinder** [comment]
I'm not seeing the same issue, did you manage to solve this?

**Comment by pelted** [comment]
Nope.. just get `command 'railsTestRunner.runAllTests' not found` now even on default install. Ended up adding my own launch config to run tests through the debugger.

**Comment by stefansedich** [comment]
@pelted I am getting `command 'railsTestRunner.runAllTests' not found` on a default install too, did you ever find a fix?
